# Generated by Django 6.0.3 on 2026-03-05 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozicija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('naziv', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pozicije',
            },
        ),
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ime', models.CharField(db_index=True, max_length=25)),
                ('prezime', models.CharField(max_length=25)),
                ('jmbg', models.CharField(max_length=13, unique=True)),
                ('broj_telefona', models.CharField(max_length=20, unique=True)),
                ('datum_zaposlenja', models.DateField()),
                ('ugovor_do', models.DateField(blank=True, null=True)),
                ('pozicija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pozicija')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zaposleni',
            },
        ),
    ]
