# Generated by Django 6.0.3 on 2026-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_zaposleni_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaposleni',
            name='datum_rodjenja',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
