# Generated by Django 6.0.3 on 2026-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_zaposleni_datum_rodjenja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaposleni',
            name='datum_rodjenja',
            field=models.DateField(),
        ),
    ]
