# Generated by Django 6.0.3 on 2026-03-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
        ('transport', '0004_alter_transport_vozac'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tip', models.CharField(choices=[('PRIJEMNICA', 'Prijemnica'), ('POVRATNICA_K', 'Povratnica od kupca'), ('OTPREMNICA', 'Otpremnica'), ('POVRATNICA_D', 'Povratnica dobavljaču'), ('MEDJUSKLADISNICA', 'Međuskladišnica'), ('PRENOS', 'Interni prenos'), ('INVENTAR', 'Popis inventara'), ('OTPIS', 'Otpisana roba')], max_length=16)),
                ('datum_vreme', models.DateTimeField()),
                ('status', models.CharField(choices=[('NACRT', 'Nacrt'), ('NA_CEKANJU', 'Na čekanju'), ('ODOBREN', 'Odobren'), ('ODBIJEN', 'Odbijen')], default='NACRT', max_length=15)),
                ('poslovni_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.poslovnipartner')),
                ('skladiste_izlaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumenti_izlaza', to='warehouse.skladiste')),
                ('skladiste_ulaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumenti_ulaza', to='warehouse.skladiste')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.transport')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.zaposleni')),
            ],
            options={
                'verbose_name_plural': 'Dokumenti',
            },
        ),
        migrations.CreateModel(
            name='StavkeDokumenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='documentss.dokument')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.proizvod')),
                ('slot_izlaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_izlaza', to='warehouse.slot')),
                ('slot_ulaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_ulaza', to='warehouse.slot')),
            ],
            options={
                'verbose_name_plural': 'Stavke Dokumenta',
                'unique_together': {('dokument', 'proizvod')},
            },
        ),
    ]
