# Generated by Django 6.0.3 on 2026-03-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('partners', '0001_initial'),
        ('transport', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tip', models.CharField(choices=[('PRIJEMNICA', 'Prijemnica'), ('POVRATNICA_K', 'Povratnica od kupca'), ('OTPREMNICA', 'Otpremnica'), ('POVRATNICA_D', 'Povratnica dobavljaču'), ('MEDJUSKLADISNICA', 'Međuskladišnica'), ('PRENOS', 'Interni prenos'), ('INVENTAR', 'Popis inventara'), ('OTPIS', 'Otpisana roba')], max_length=16)),
                ('datum_vreme', models.DateTimeField()),
                ('poslovni_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.poslovnipartner')),
                ('skladiste_izlaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumenti_izlaza', to='warehouse.skladiste')),
                ('skladiste_ulaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumenti_ulaza', to='warehouse.skladiste')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.transport')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.zaposleni')),
            ],
            options={
                'verbose_name_plural': 'Dokumenti',
            },
        ),
    ]
