# Generated by Django 6.0.3 on 2026-03-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentss', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StavkeDokumenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentss.dokument')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.proizvod')),
            ],
            options={
                'verbose_name_plural': 'Stavke Dokumenta',
                'unique_together': {('dokument', 'proizvod')},
            },
        ),
    ]
