# Generated by Django 6.0.3 on 2026-03-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentss', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavkedokumenta',
            name='slot_izlaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stavke_izlaza', to='warehouse.slot'),
        ),
        migrations.AlterField(
            model_name='stavkedokumenta',
            name='slot_ulaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stavke_ulaza', to='warehouse.slot'),
        ),
    ]
