# Generated by Django 6.0.3 on 2026-04-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentss', '0002_alter_stavkedokumenta_slot_izlaza_and_more'),
        ('warehouse', '0003_alter_slot_kapacitet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stavkedokumenta',
            name='slot_izlaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stavke_izlaza', to='warehouse.slot'),
        ),
        migrations.AlterField(
            model_name='stavkedokumenta',
            name='slot_ulaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stavke_ulaza', to='warehouse.slot'),
        ),
    ]
