# Generated by Django 6.0.3 on 2026-05-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_zaposleni_datum_rodjenja'),
        ('documentss', '0003_alter_stavkedokumenta_slot_izlaza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='datum_odluke',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokument',
            name='odobrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odobreni_dokumenti', to='accounts.zaposleni'),
        ),
    ]
