# Generated by Django 6.0.3 on 2026-03-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skladiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('naziv', models.CharField(db_index=True, max_length=50)),
                ('adresa', models.CharField(max_length=50, unique=True)),
                ('telefon', models.CharField(max_length=20, unique=True)),
                ('tip', models.CharField(choices=[('DIST', 'Distributivni centar'), ('VELE', 'Veleprodajno skladište'), ('MALO', 'Maloprodajni magacin'), ('TRAN', 'Tranzit')], max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Skladišta',
            },
        ),
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('naziv', models.CharField(max_length=50)),
                ('skladiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.skladiste')),
            ],
            options={
                'verbose_name_plural': 'Sektori',
                'unique_together': {('naziv', 'skladiste')},
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('naziv', models.CharField(max_length=50)),
                ('sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.sektor')),
            ],
            options={
                'verbose_name_plural': 'Slotovi',
                'unique_together': {('naziv', 'sektor')},
            },
        ),
    ]
