# Generated by Django 6.0.3 on 2026-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='kapacitet',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
