# Generated by Django 6.0.3 on 2026-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_skladiste_naziv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladiste',
            name='naziv',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
