# Generated by Django 6.0.3 on 2026-03-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('naziv', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategorije',
            },
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('naziv', models.CharField(max_length=50, unique=True)),
                ('barkod', models.CharField(max_length=32, unique=True)),
                ('sifra', models.CharField(db_index=True, max_length=50, unique=True)),
                ('jedinica_mere', models.CharField(choices=[('g', 'gram'), ('kg', 'kilogram'), ('t', 'tona'), ('ml', 'mililitar'), ('l', 'litar'), ('kol', 'količina')], max_length=3)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.kategorija')),
            ],
            options={
                'verbose_name_plural': 'Proizvodi',
            },
        ),
        migrations.CreateModel(
            name='Zalihe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rezervisana_kolicina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.proizvod')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.slot')),
            ],
            options={
                'unique_together': {('proizvod', 'slot')},
            },
        ),
    ]
