# Generated by Django 6.0.3 on 2026-04-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zalihe',
            options={'verbose_name_plural': 'Zalihe'},
        ),
    ]
