# Generated by Django 6.0.3 on 2026-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_zalihe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zalihe',
            name='kolicina',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zalihe',
            name='rezervisana_kolicina',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
