# Generated by Django 6.0.3 on 2026-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_zalihe_kolicina_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='nabavna_cena',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
    ]
