# Generated by Django 6.0.3 on 2026-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_proizvod_nabavna_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='nabavna_cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
