# Generated by Django 6.0.3 on 2026-03-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=50)),
                ('registarski_broj', models.CharField(db_index=True, max_length=15, unique=True)),
                ('datum_registracije', models.DateField()),
                ('poslednji_tehnicki', models.DateField()),
                ('zaduzeni_vozac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.zaposleni')),
            ],
            options={
                'verbose_name_plural': 'Vozila',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datum_polaska', models.DateField()),
                ('datum_zavrsetka', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ZAKAZANO', 'Zakazano'), ('U_TOKU', 'U toku'), ('ZAVRSENO', 'Završeno'), ('OTKAZANO', 'Otkazano'), ('NEUSPESNO', 'Neuspešno')], max_length=9)),
                ('napomena', models.TextField(blank=True, null=True)),
                ('vozac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.zaposleni')),
                ('vozilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vozilo')),
            ],
            options={
                'verbose_name_plural': 'Transporti',
            },
        ),
    ]
