# Generated by Django 6.0.3 on 2026-03-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='datum_polaska',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='datum_zavrsetka',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
