# Generated by Django 6.0.3 on 2026-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transport_datum_polaska_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='datum_polaska',
            field=models.DateTimeField(),
        ),
    ]
