# Generated by Django 6.0.3 on 2026-03-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transport', '0003_alter_transport_datum_polaska'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='vozac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.zaposleni'),
        ),
    ]
