# Generated by Django 6.0.3 on 2026-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoslovniPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('naziv', models.CharField(db_index=True, max_length=50)),
                ('pib', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresa', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('tip', models.CharField(choices=[('D', 'Dobavljač'), ('K', 'Kupac')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Poslovni Partneri',
            },
        ),
    ]
